In [ ]:
import timeit
import math 
import numpy as np


start = timeit.default_timer()


#Finding 3rd primitive root of unity
roots= np.roots([1, 0, 0, -1])
w=roots[0]


# program body starts

#DFT of A_4 matrix
DFT_A4 =np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
         [1, w, w**2, 1, w, w**2, 1, w, w**2, 1, w, w**2], 
         [1, w**2, w, 1, w**2, w, 1, w**2, w, 1, w**2, w],  
         [1, 0, 0, 1, 0, 0, -1, 0, 0, -1, 0, 0], 
         [0, 0, -1, 0, 0, 1, 0, 0, 1, 0, 0, -1], 
         [0, -1, 0, 0, 1, 0, 0 , 1, 0, 0, -1, 0], 
         [0, -1, 0, 0, 1, 0, 0 , -1, 0, 0, 1, 0], 
         [1, 0, 0, -1, 0, 0, 1, 0, 0, -1, 0, 0], 
         [0, 0, 1, 0, 0, -1, 0, 0, 1, 0, 0, -1], 
         [0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0, 1], 
         [0, 1, 0, 0, 1, 0, 0 , -1, 0, 0, -1, 0], 
         [1, 0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0]])

#Defining a function f: A_4 ->A_4
f=np.array([ [-6],[ 9], [-7], [0], [1], [-3], [5], [0], [3], [1], [7], [-1]])
print(f"Entered function is f = \n" ,np.transpose(f))


#Finding discrete fourier transform by performing F= DFT_A5*transpose(f)

F=np.matmul(DFT_A4, f)

print(f"Discrete fourier transform od f is \n", np.transpose(F))

stop = timeit.default_timer()

# program body ends

# total time taken
print(f"Runtime of the program is ", stop - start)


Entered function is f = 
 [[-6  9 -7  0  1 -3  5  0  3  1  7 -1]]
Discrete fourier transform od f is 
 [[  9.  +0.j          -4.5+21.65063509j  -4.5-21.65063509j
  -12.  +0.j           8.  +0.j         -15.  +0.j
   -1.  +0.j          -2.  +0.j           0.  +0.j
   12.  +0.j           3.  +0.j         -10.  +0.j        ]]
Runtime of the program is  0.0028487840000082087


In [ ]:
import timeit
import math 
import numpy as np


start = timeit.default_timer()
roots= np.roots([1, 0, 0, -1])
w=roots[0]


# program body starts

#DFT of A_4 matrix
DFT_A4 =np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
         [1, w, w**2, 1, w, w**2, 1, w, w**2, 1, w, w**2], 
         [1, w**2, w, 1, w**2, w, 1, w**2, w, 1, w**2, w],  
         [1, 0, 0, 1, 0, 0, -1, 0, 0, -1, 0, 0], 
         [0, 0, -1, 0, 0, 1, 0, 0, 1, 0, 0, -1], 
         [0, -1, 0, 0, 1, 0, 0 , 1, 0, 0, -1, 0], 
         [0, -1, 0, 0, 1, 0, 0 , -1, 0, 0, 1, 0], 
         [1, 0, 0, -1, 0, 0, 1, 0, 0, -1, 0, 0], 
         [0, 0, 1, 0, 0, -1, 0, 0, 1, 0, 0, -1], 
         [0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0, 1], 
         [0, 1, 0, 0, 1, 0, 0 , -1, 0, 0, -1, 0], 
         [1, 0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0]])

#D_A3 matrix

D_A3 =np.array([[1 , 1 , 1 , 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[1 ,  w ,  w**2 , 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[1 ,  w**2 ,  w , 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[0, 0, 0, 1 , 1 , 1 , 0, 0, 0, 0, 0, 0], 
[0, 0, 0, 1 ,  w,  w**2 , 0, 0, 0, 0, 0, 0], 
[0, 0, 0, 1 ,  w**2 ,  w , 0, 0, 0, 0, 0, 0], 
[0, 0, 0, 0, 0, 0, 1 , 1 , 1 , 0, 0, 0], 
[ 0, 0, 0, 0, 0, 0, 1 ,  w ,  w**2 , 0, 0, 0], 
[0, 0, 0, 0, 0, 0, 1 ,  w**2 ,  w , 0, 0, 0], 
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1 , 1 , 1 ], 
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ,  w ,  w**2 ] ,
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ,  w**2 ,  w ]])


#Calculating F_A4 matrix

F_A4 = np.matmul(DFT_A4, np.linalg.inv(D_A3))


#Defining a function f: A_5 ->A_5
f=np.array([ [-6],[ 9], [-7], [0], [1], [-3], [5], [0], [3], [1], [7], [-1]])
print(f"Entered function is f = \n" ,np.transpose(f))

#Finding discrete fourier transform by performing F= DFT_A5*transpose(f)

F=np.matmul(np.matmul(F_A4, D_A3), f)
print(f"Discrete fourier transform od f is \n", np.transpose(F))

stop = timeit.default_timer()

# program body ends

# total time taken
print(f"Runtime of the program is ", stop - start)


Entered function is f = 
 [[-6  9 -7  0  1 -3  5  0  3  1  7 -1]]
Discrete fourier transform od f is 
 [[  9. -1.20185168e-15j  -4.5+2.16506351e+01j  -4.5-2.16506351e+01j
  -12. -5.64007398e-16j   8. -1.11805099e-15j -15. -9.63617178e-16j
   -1. -9.38470925e-17j  -2. -1.70827256e-16j   0. +4.49307856e-17j
   12. -8.00926172e-16j   3. -3.84592537e-16j -10. -2.59675926e-15j]]
Runtime of the program is  0.008518042000005721


In [ ]:

a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
np.matmul(np.linalg.inv(a), a)


array([[ 1.00000000e+00, -2.77555756e-16, -6.10622664e-16],
       [ 0.00000000e+00,  1.00000000e+00,  2.77555756e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
!pip install big-O
import big_o
#Generating random test strings of length 100
sample_strings = lambda n: big_o.datagen.strings(100)
#my logic to find the first non-repetitive character in the string
def non_repetitive(sample_string):
    string_list = list(sample_string)
    non_repetitive_char = next((ele for ele in string_list if string_list.count(ele)==1),None)
    return non_repetitive_char
#Calculating the Time complexity
best, others = big_o.big_o(non_repetitive, sample_strings,n_measures=20)
print(best)

  Created wheel for big-O: filename=big_O-0.10.2-py3-none-any.whl size=10035 sha256=12f4c2ce7aaebdc57d23e2de746e44c33f59685feccf37b88309244ebbb2236e
  Stored in directory: /root/.cache/pip/wheels/b6/29/d2/fb6530b47b5e4f1b5b4655e3dd53b1d609a1978cf7d6880077
Successfully built big-O
Constant: time = 2.5E-05 (sec)
